@hostname = http://localhost:9532

### health
GET {{hostname}}/health


### check User
GET {{hostname}}/auth/check-user?email=email@email.com

### get redis
GET {{hostname}}/redis/prueba255231347
X-Type-Value: object

